### ISSUE TITLE
Возможность установить дату доклада на странице редактирования презентации

### ISSUE THREAD

**Issue by zmm** [OSLL/android_public_speech_trainer#172]
Добавьте необязательное для заполнения поле "Дата доклада".
Расширьте модель для хранения этого поля
Добавьте Espresso-тест для проверки работы с этим полем.

**Comment by zmm** [comment]
1. Не пройдена проверка в TRavis. 
2. Тесты падают:
```

java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
at android.arch.persistence.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.java:135)
at android.arch.persistence.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:115)
at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:151)
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:266)
at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:96)
at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:54)
at android.arch.persistence.room.RoomDatabase.query(RoomDatabase.java:233)
at com.example.putkovdimi.trainspeech.DBTables.DaoInterfaces.PresentationDataDao_Impl.getAll(PresentationDataDao_Impl.java:200)
at com.example.company.myapplication.StartPageActivity.refreshRecyclerView(StartPageActivity.kt:114)
at com.example.company.myapplication.StartPageActivity.onStart(StartPageActivity.kt:266)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
at android.support.test.runner.MonitoringInstrumentation.callActivityOnStart(MonitoringInstrumentation.java:679)
at android.app.Activity.performStart(Activity.java:6883)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2686)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2784)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:163)
at android.app.ActivityThread.main(ActivityThread.java:6238)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)


java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.company.myapplication/com.example.company.myapplication.StartPageActivity}: java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2723)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2784)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:163)
at android.app.ActivityThread.main(ActivityThread.java:6238)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
Caused by: java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
at android.arch.persistence.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.java:135)
at android.arch.persistence.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:115)
at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:151)
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:266)
at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:96)
at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:54)
at android.arch.persistence.room.RoomDatabase.query(RoomDatabase.java:233)
at com.example.putkovdimi.trainspeech.DBTables.DaoInterfaces.PresentationDataDao_Impl.getAll(PresentationDataDao_Impl.java:200)
at com.example.company.myapplication.StartPageActivity.refreshRecyclerView(StartPageActivity.kt:114)
at com.example.company.myapplication.StartPageActivity.onStart(StartPageActivity.kt:266)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
at android.support.test.runner.MonitoringInstrumentation.callActivityOnStart(MonitoringInstrumentation.java:679)
at android.app.Activity.performStart(Activity.java:6883)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2686)
... 9 more

Test running failed: Instrumentation run failed due to 'Process crashed.'

```

**Comment by zmm** [comment]
Ошибка с тестами была моим локальным багом, который вылечился полной переустановкой. 
Я внимательно потестировал этот интерфейс на своем устройстве и составил список правок, которые необходимо добавить. Общая цель - сделать оформление единообразным и повысить удобство.
На текущий момент необходимо поправить:
- убрать возможность поставить дату ДО текущей,
- дефолтное значение "Даты доклада" + 7 дней к текущей дате
- давайте расположим элемент выбора даты и checkbox друг над другом (оба они расположены под "Ограничение времени на доклад") - пусть будет прокрутка.

**Comment by zmm** [comment]
Поправьте, пожалуйста, конфликты.

**Comment by zmm** [comment]
Для теста setDateForPresentation вот такая ошибка
android.support.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with text: is "2035-5-12"
