### ISSUE TITLE
Баг с просмотром статистики тренировки

### ISSUE THREAD

**Issue by zmm** [OSLL/android_public_speech_trainer#319]
При нажатии на элемент истории тренировок у anton.filatov (в слаке) возникает ошибка. 
Предположительно, пользователь заменял содержимое файла презентации на устройстве после ее добавления в приложение.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.spb.speech/ru.spb.speech.TrainingStatisticsActivity}: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.io.InputStream
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2814)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
    at android.app.ActivityThread.-wrap11(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1613)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:176)
    at android.app.ActivityThread.main(ActivityThread.java:6635)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.io.InputStream
    at ru.spb.speech.appSupport.PdfToBitmap.initRenderer(PdfToBitmap.kt:81)
    at ru.spb.speech.appSupport.PdfToBitmap.<init>(PdfToBitmap.kt:38)
    at ru.spb.speech.TrainingStatisticsActivity.onCreate(TrainingStatisticsActivity.kt:101)
    at android.app.Activity.performCreate(Activity.java:7084)
    at android.app.Activity.performCreate(Activity.java:7075)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2767)
    ... 9 more
```

**Comment by Evgenijjjj** [comment]
https://github.com/OSLL/android_public_speech_trainer/blob/master/app/src/main/java/ru/spb/speech/appSupport/PdfToBitmap.kt#L80
