### ISSUE TITLE
AdditionalCountdownTimerTest падает с ошибкой 

### ISSUE THREAD

**Issue by zmm** [OSLL/android_public_speech_trainer#325]
![image](https://user-images.githubusercontent.com/717575/56034160-38d77080-5d2f-11e9-81ef-5ce5d4f29d08.png)

java.lang.IllegalArgumentException: Service not registered: android.speech.SpeechRecognizer$Connection@ca34f6e
at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1289)
at android.app.ContextImpl.unbindService(ContextImpl.java:1511)
at android.content.ContextWrapper.unbindService(ContextWrapper.java:648)
at android.speech.SpeechRecognizer.destroy(SpeechRecognizer.java:408)
at ru.spb.speech.SpeechRecognitionService.onDestroy(SpeechRecognitionService.kt:119)
at android.app.ActivityThread.handleStopService(ActivityThread.java:3327)
at android.app.ActivityThread.-wrap27(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6077)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by zmm** [comment]
+ Необходимо добавить настройку permissions
